version: '3.9'

services:
  postgres:
    image: postgres
    container_name: storefront_backend
    ports:
      - '5416:5432'
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres:
